default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  timeout: 5000

development:
  <<: *default
  database: simpleshop_development

test:
  <<: *default
  database: simpleshop_test

production:
  <<: *default
  database: simpleshop_production
